In [21]:
%reset -f
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

######## import GKROM class from GKROM file ########
%run "xxx/GKROM.ipynb" import GKROM

In [22]:
######## <Scenario 1>: Target sample generated From a multivariate normal distriution ########
# target sample
M = np.random.multivariate_normal(np.zeros(3), np.diag(np.ones(3)), size = 1000) 

### <Case1>: no save to file, match only skewness, fixed omega ###
# match4 = False
# result = GKROM(M, path = None, folder_name = None, simuSize = None, match4 = match4)

### <Case2>: no save to file, match skewness and kurtosis ###
match4 = True
result = GKROM(M, path = None, folder_name = None, simuSize = None, match4 = match4)

### compute simulated sample ###
result.run()

### pull the simulated sample ###
result.output 

Column 1 completed...
Column 2 completed...
Column 3 completed...
Core code running time: 1.04 seconds


array([[ 0.6579987 , -1.54736056, -0.61600827],
       [ 0.98711656,  0.68167999,  0.1082831 ],
       [-0.95745095, -1.75205151,  2.02117219],
       ...,
       [ 0.2867548 ,  0.02388143, -0.65230423],
       [-0.74375929,  0.04557885,  0.48753245],
       [-0.29996862,  1.1294226 ,  2.26941616]])

In [13]:
######## <Scenario 2>: Target sample came from a real dataset ########
M = pd.read_csv(r'data.csv', header = None)
M = np.array(M)

### <Case3>: no file saved, match skewness, random omega ###
match4 = False
result = GKROM(M, path = None, folder_name = None, simuSize = None, match4 = match4, fixedOmega = False)

### <Case4>: no file saved, match skewness and kurtosis, random omega ###
### Warning: When the target is real data, matching the first four moments is very slow
# match4 = True
# result = GKROM(M, path = path, folder_name = None, simuSize = None, match4 = match4, fixedOmega = False)

### compute simulated sample ###
result.run()

### pull the simulated sample ###
result.output

array([[-0.00582515, -0.00862573, -0.01382892],
       [ 0.00084208,  0.00200499,  0.00967353],
       [ 0.00594085,  0.01022693,  0.0208186 ],
       ...,
       [-0.00525285,  0.00500284,  0.01660831],
       [ 0.00028906,  0.00347203,  0.00478849],
       [-0.00480783, -0.00403467, -0.00535692]])

In [20]:
######### check whether the simulated sample has the same skewness and/or kurtosis as the target #########
print( result.Kolloskewness(result.stdized_output) - result.b)
if match4:
    print(result.Kollokurtosis(result.stdized_output) - result.K)

[[-2.26707521e-07]
 [-2.26707449e-07]
 [-2.17627075e-07]]
[[8.59347491e-07 5.99646340e-06 3.08308827e-06]
 [5.99646340e-06 8.53006319e-07 3.08942943e-06]
 [3.08308827e-06 3.08942943e-06 3.78300482e-06]]
